### PR TITLE
Improve score board GUI

### PR DESCRIPTION
**Pull request by ZwerOxotnik**

### CODE REVIEW

**Comment by blubFisch** [comment]
Looks good.

Is this MP tested already?

Also, can you please open the window to left middle like this.

image

**Comment by blubFisch** [comment]
It should open below the tutorial. Also I think we can open it by default (on join) now because it's easy to close.

**Comment by ZwerOxotnik** [comment]
> Also, can you please open the window to left middle like this.

yes

> It should open below the tutorial. 

There are issues with that.

> It should open below the tutorial. Also I think we can open it by default (on join) now because it's easy to close.

You already have a start GUI that fills the screen fully at start.

> Is this MP tested already?

I do not use 2 PC etc. at the same time, nonetheless, the server had been running with changes. It should be fine.

**Comment by blubFisch** [comment]
Is this PR ready to merge?

**Comment by ZwerOxotnik** [comment]
@blubFisch
image

**Comment by ZwerOxotnik** [comment]
Yeah

**Comment by ZwerOxotnik** [comment]
wait, nope

**Comment by ZwerOxotnik** [comment]
It should be fine now.

**Comment by blubFisch** [comment]
Thanks!

**Pull request merged**
