### PR TITLE
Add anti train abuse

### PR DESCRIPTION
**Pull request by ZwerOxotnik**

### CODE REVIEW

**Comment by blubFisch** [comment]
Tested, looks good. Can you please add an error message to the player for it?

**Comment by ZwerOxotnik** [comment]
Yes.

**Comment by ZwerOxotnik** [comment]
Don't merge, it doesn't work properly at all.

**Comment by ZwerOxotnik** [comment]
@blubFisch, it should work properly now.

**Comment by blubFisch** [comment]
Thanks!

**Pull request merged**
